// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ_-3BLwGni9Jd5GuuY2PwPBNJtzKQWzo',
    appId: '1:164349199073:web:9fc245e8944ba37c77ada0',
    messagingSenderId: '164349199073',
    projectId: 'fyp-mha',
    authDomain: 'fyp-mha.firebaseapp.com',
    storageBucket: 'fyp-mha.firebasestorage.app',
    measurementId: 'G-KW88H11M39',
    databaseURL:
        'https://fyp-mha-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvegduFaK8tkASOb_O6xgl5sbzLlEMDQg',
    appId: '1:164349199073:android:f34d1f4ff1f7289377ada0',
    messagingSenderId: '164349199073',
    projectId: 'fyp-mha',
    storageBucket: 'fyp-mha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLUDimaALbs2PTu7-Gu45l-LxG_1Oa5jY',
    appId: '1:164349199073:ios:df98a74d777b32aa77ada0',
    messagingSenderId: '164349199073',
    projectId: 'fyp-mha',
    storageBucket: 'fyp-mha.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLUDimaALbs2PTu7-Gu45l-LxG_1Oa5jY',
    appId: '1:164349199073:ios:df98a74d777b32aa77ada0',
    messagingSenderId: '164349199073',
    projectId: 'fyp-mha',
    storageBucket: 'fyp-mha.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ_-3BLwGni9Jd5GuuY2PwPBNJtzKQWzo',
    appId: '1:164349199073:web:3fd8b99c65682e5177ada0',
    messagingSenderId: '164349199073',
    projectId: 'fyp-mha',
    authDomain: 'fyp-mha.firebaseapp.com',
    storageBucket: 'fyp-mha.firebasestorage.app',
    measurementId: 'G-8YRQV28NCL',
  );
}
